version: '3.8'

services:
  tts_tilern:
    build: .
    container_name: tts_tilern
    restart: unless-stopped
    ports:
      - '8400:8400'
    volumes:
      - ./models/de:/app/models/de
      - ./public:/app/public
    networks:
      - shared_network

networks:
  shared_network:
    external: true
